[2025-10-16T13:57:03.149+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T13:57:03.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_task.task_sql manual__2025-10-16T13:56:53.683473+00:00 [queued]>
[2025-10-16T13:57:03.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_task.task_sql manual__2025-10-16T13:56:53.683473+00:00 [queued]>
[2025-10-16T13:57:03.185+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T13:57:03.215+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_sql> on 2025-10-16 13:56:53.683473+00:00
[2025-10-16T13:57:03.228+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T13:57:03.230+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-10-16T13:57:03.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'email_task', 'task_sql', 'manual__2025-10-16T13:56:53.683473+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/email_task.py', '--cfg-path', '/tmp/tmp1ig6nee1']
[2025-10-16T13:57:03.233+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask task_sql
[2025-10-16T13:57:03.244+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-16T13:57:03.284+0000] {task_command.py:426} INFO - Running <TaskInstance: email_task.task_sql manual__2025-10-16T13:56:53.683473+00:00 [running]> on host a31b0a3647d9
[2025-10-16T13:57:03.385+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_task' AIRFLOW_CTX_TASK_ID='task_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T13:56:53.683473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T13:56:53.683473+00:00'
[2025-10-16T13:57:03.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T13:57:17.220+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T13:57:17.221+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/email_task.py", line 9, in connect_to_sqlserver
    conn = pyodbc.connect(
           ^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
[2025-10-16T13:57:17.234+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=email_task, task_id=task_sql, run_id=manual__2025-10-16T13:56:53.683473+00:00, execution_date=20251016T135653, start_date=20251016T135703, end_date=20251016T135717
[2025-10-16T13:57:17.246+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task task_sql (('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)'); 207)
[2025-10-16T13:57:18.353+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T13:57:18.367+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T13:57:18.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
