[2025-10-16T13:52:00.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T13:52:00.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_task.task_sql scheduled__2025-10-16T13:45:00+00:00 [queued]>
[2025-10-16T13:52:00.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_task.task_sql scheduled__2025-10-16T13:45:00+00:00 [queued]>
[2025-10-16T13:52:00.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T13:52:00.692+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_sql> on 2025-10-16 13:45:00+00:00
[2025-10-16T13:52:00.701+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T13:52:00.703+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-10-16T13:52:00.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'email_task', 'task_sql', 'scheduled__2025-10-16T13:45:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/email_task.py', '--cfg-path', '/tmp/tmpx7o481a9']
[2025-10-16T13:52:00.710+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask task_sql
[2025-10-16T13:52:00.724+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-16T13:52:00.772+0000] {task_command.py:426} INFO - Running <TaskInstance: email_task.task_sql scheduled__2025-10-16T13:45:00+00:00 [running]> on host a31b0a3647d9
[2025-10-16T13:52:00.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_task' AIRFLOW_CTX_TASK_ID='task_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T13:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T13:45:00+00:00'
[2025-10-16T13:52:00.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T13:52:00.877+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T13:52:00.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/email_task.py", line 9, in connect_to_sqlserver
    conn = pyodbc.connect(
           ^^^^^^^^^^^^^^^
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
[2025-10-16T13:52:00.896+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=email_task, task_id=task_sql, run_id=scheduled__2025-10-16T13:45:00+00:00, execution_date=20251016T134500, start_date=20251016T135200, end_date=20251016T135200
[2025-10-16T13:52:00.911+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task task_sql (('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)"); 198)
[2025-10-16T13:52:00.924+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T13:52:00.948+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T13:52:00.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
