[2025-10-16T11:36:13.819+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T11:36:13.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Depi.task3 manual__2025-10-16T11:36:07.985511+00:00 [queued]>
[2025-10-16T11:36:13.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Depi.task3 manual__2025-10-16T11:36:07.985511+00:00 [queued]>
[2025-10-16T11:36:13.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T11:36:13.854+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task3> on 2025-10-16 11:36:07.985511+00:00
[2025-10-16T11:36:13.862+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-16T11:36:13.863+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2025-10-16T11:36:13.863+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Depi', 'task3', 'manual__2025-10-16T11:36:07.985511+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_depi.py', '--cfg-path', '/tmp/tmp5z9qe2za']
[2025-10-16T11:36:13.865+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask task3
[2025-10-16T11:36:13.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-16T11:36:13.905+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Depi.task3 manual__2025-10-16T11:36:07.985511+00:00 [running]> on host a31b0a3647d9
[2025-10-16T11:36:13.965+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Depi' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T11:36:07.985511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T11:36:07.985511+00:00'
[2025-10-16T11:36:13.966+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T11:36:13.968+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T11:36:13.968+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Airflow_depi.py", line 9, in save_file
    with open("/opt/airflow/shared/tmp/random.txt", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/shared/tmp/random.txt'
[2025-10-16T11:36:13.982+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Depi, task_id=task3, run_id=manual__2025-10-16T11:36:07.985511+00:00, execution_date=20251016T113607, start_date=20251016T113613, end_date=20251016T113613
[2025-10-16T11:36:13.991+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 109 for task task3 ([Errno 2] No such file or directory: '/opt/airflow/shared/tmp/random.txt'; 85)
[2025-10-16T11:36:14.038+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T11:36:14.053+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T11:36:14.055+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
